Feature/admin methods
proepidesenvolvimento/guardioes-api pull request #209
Opened 2020-11-19 04:35 UTC by emanuks

This PR adds admin methods for management through the panel.

2020-11-23 23:00 UTC, ViniciusPuerto requested changes

2020-11-23 23:00 UTC, ViniciusPuerto commented on db/schema.rb
> -    t.bigint "permission_id"
Acho que isso não pode ser deletado assim como as outras relações com permissões

2020-11-23 23:07 UTC, emanuks commented on db/schema.rb
> -    t.bigint "permission_id"
Vou realizar o merge com a develop, isso deve resolver esse problema de deleção

2020-11-24 01:06 UTC, ViniciusPuerto approved these changes

2020-11-24 01:06 UTC, merged