CRUD de vacinas
proepidesenvolvimento/guardioes-api pull request #320
Opened 2021-07-27 14:10 UTC by jps12

**Descrição**<br>
Foi criado a migration, a model, validações, controller e as rotas. O CRUD de forma geral de vacinas 

**Como testar**<br>
Sem autentiação: Comente a linha que autentica como admin e faça uma requisição simples 
Com auteticação: Faça autenticação como admin e colete o token e o use para acessar as rotas de vacinas.

**Resultados esperados**<br>
O programa deve ser capaz de retornar a(s) vacina(s) nas rotas get
Deve ser capaz de atualizar corretamente nas rotas PATCH/PUT
DEve ser capaz de apagar corretamente na rota DELETE
Deve ser capaz de criar corretamente na rota POST

**Checklist**
- [x] Código compila corretamente (Se aplicável);
- [ ] Mudanças realizadas foram testadas e passaram no testes (Se aplicável);
- [ ] Documentos gerados/atualizados (Se aplicável);
- [x] Feito por conta própria (Se aplicável).

2021-07-28 18:03 UTC, alvesitalo commented on app/controllers/vaccines_controller.rb
> +      @vaccines = Vaccine.all
Aqui é necessário filtrar as vacinas pelo app_id do usuário atual, da mesma forma que acontece com os Contents ou Syndromes

2021-07-28 18:08 UTC, alvesitalo commented on app/controllers/vaccines_controller.rb
> +        params.permit(
Aqui você precisa aceitar um objeto de vacina como parâmetro (`params.require(:vaccine).permit(`). Aí seria legal você deixar um exemplo de objeto em "Como testar" e a rota tbm que precisa dar o POST, ficaria bem explicado.

2021-07-28 18:15 UTC, alvesitalo commented on app/controllers/vaccines_controller.rb
> +        params.permit(
Isso também implica nas rotas que estão apenas retornando um array ou objeto, sem especificar o tipo dele.
Ex:
- Resposta identificando que é um array de Households:
![Captura de Tela 2021-07-28 às 15 04 33](https://user-images.githubusercontent.com/35741521/127374665-a673f9cf-2f39-4475-b638-0d653cd23045.png)

- Resposta atual das Vacinas:
![Captura de Tela 2021-07-28 às 15 04 44](https://user-images.githubusercontent.com/35741521/127374765-0a1ce19f-f651-490b-bcaf-6d6b14184dc0.png)

2021-07-28 18:18 UTC, alvesitalo requested changes
Deixei alguns comentários do que precisa ser mudado. Você pode dar uma olhada no comportamento de outras controllers também :grinning:

2021-07-29 04:44 UTC, jps12 commented on app/controllers/vaccines_controller.rb
> +    before_action :authenticate_admin!
Isso foi resolvido pelo arquivo de ability

2021-07-29 04:46 UTC, jps12 commented on app/controllers/vaccines_controller.rb
> +      @vaccines = Vaccine.all
Foi filtrado por uma função aplicado na model de vacinas

2021-07-29 04:49 UTC, jps12 commented
A fim de deixar documentado. Apenas o admin vai poder gerenciar (criar, atualizar e deletar) as vacinas, enquanto o usuário comum irá poder apenas vizualizar.

2021-07-29 13:50 UTC, jps12 commented
Todas as sugestões foram acatadas e colocadas em prática. com relação ao identificador do que é o array, era a falta da serializer que era a causa.

2021-07-29 15:33 UTC, alvesitalo approved these changes

2021-07-29 15:33 UTC, merged