Fix Permissions
ProEpiDesenvolvimento/guardioes-api pull request #357
Opened 2021-11-09 18:51 UTC by alvesitalo

**Descrição**<br>
Corrige permissões de alguns usuários na API.<br>

**Como testar**<br>
Utilizar essa branch e abrir o Painel e logar com todos os tipos de usuário, testando as ações de cada um, em cada aba disponível.

**Resultados esperados**<br>
Permissões funcionando corretamente.

**Checklist**
- [x] Código compila corretamente (Se aplicável);
- [ ] Mudanças realizadas foram testadas e passaram no testes (Se aplicável);
- [ ] Documentos gerados/atualizados (Se aplicável);
- [ ] Feito por conta própria (Se aplicável).

2021-12-03 18:43 UTC, EduardoMdR commented
Olá @alvesitalo, acabei de revisar essa PR utilizando o Painel web para isso, aqui segue alguns conflitos que encontrei quando fui testar

## Logado como Admin ##

### Geral ####
- [ ]  Quando a senha é um campo que está invalido, a mensagem de erro diz apenas que tem algum erro, e não que a senha está curta por exemplo

### Visualizações ###
- [ ]  Sempre aparece uma mensagem de 'Não foi possível conectar'

### Gerentes ###
- [ ]  Não consigo adicionar/editar/visualizar as permissões do gerente (mas essas permissões estão funcionando)

### Gerente Instituições ###
- [ ]  Não consigo selecionar um País ou Estado

### Sintomas ###
- [ ]  Não tem nenhum alert ao Criar e Excluir (talvez seja proposital)

### Síndromes ###
- [ ]  Não foi possível criar

## Não consegui acessar Instituição e Equipe de Instituição ##

## Faça Parte ##
- Por mais que talvez não faça parte da Issue, acho valido comentar aqui. Quando tento criar uma nova instituição (na página faça parte) sempre aparece o alert de erro (mas aparentemente cria a instituição)

2021-12-03 18:46 UTC, EduardoMdR requested changes
Olá @alvesitalo, acabei de revisar essa PR utilizando o Painel web para isso, aqui segue alguns conflitos que encontrei quando fui testar

## Logado como Admin ##

### Geral ####
- [x]  Quando a senha é um campo que está invalido, a mensagem de erro diz apenas que tem algum erro, e não que a senha está curta por exemplo

### Visualizações ###
- [x]  Sempre aparece uma mensagem de 'Não foi possível conectar'

### Gerentes ###
- [ ]  Não consigo adicionar/editar/visualizar as permissões do gerente (mas essas permissões estão funcionando)

### Gerente Instituições ###
- [x]  Não consigo selecionar um País ou Estado

### Sintomas ###
- [ ]  Não tem nenhum alert ao Criar e Excluir (talvez seja proposital)

### Síndromes ###
- [x]  Não foi possível criar

## Não consegui acessar Instituição e Equipe de Instituição ##

## Faça Parte ##
- Por mais que talvez não faça parte da Issue, acho valido comentar aqui. Quando tento criar uma nova instituição (na página faça parte) sempre aparece o alert de erro (mas aparentemente cria a instituição)

2021-12-06 12:33 UTC, alvesitalo commented
@EduardoMdR Alguns erros que você teve são algumas configurações que estão faltando. Na parte de Visualizações, você precisa colocar as duas variáveis do Metabase no seu .env para carregar elas. Na parte de Gerentes de Intituição, para selecionar País ou Estado, você precisa criar esses grupos pela rota `/groups/build_country_city_state_groups` ou pelo console para que eles apareçam. No Faça Parte você precisa setar as três variáveis do Mailer no seu .env (se notar o erro foi porque o email não foi enviado).

2021-12-06 12:39 UTC, alvesitalo commented
Já sobre o erro em Gerentes, o seu Admin é god? Testei novamente e não encontrei nenhum erro com eles... Como você fez para testar?

2021-12-06 19:04 UTC, EduardoMdR approved these changes

2021-12-06 19:06 UTC, merged